# EDA : 수치형, 범주형 기술통계

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [4]:
np.array([[1, 2],
          [3, 4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [6]:
np.array([1, 2, 3, 4]).reshape((2, 2))

array([[1, 2],
       [3, 4]])

In [7]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array[0]

array([1, 2, 3])

In [10]:
array[1]

array([4, 5, 6])

In [11]:
array[1][1]

5

In [12]:
array[1, 1] # row index, col index

5

In [13]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array.ndim  # number of dimension

2

In [15]:
array.shape

(2, 3)

In [16]:
array.sum()

21

In [17]:
array.std() # standard deviation, 표준편차

1.707825127659933

In [18]:
array.var() # variance, 분산

2.9166666666666665

In [19]:
nums = np.array([1, 2, 2, 3])
nums

array([1, 2, 2, 3])

In [20]:
set(nums)

{1, 2, 3}

In [21]:
len(nums)

4

In [22]:
np.unique(nums)

array([1, 2, 3])

In [23]:
len(np.unique(nums))

3

In [24]:
np.arange(start=5, stop=20, step=5)

array([ 5, 10, 15])

In [25]:
nums

array([1, 2, 2, 3])

In [26]:
np.where(nums==2, "ok!", "no!")

array(['no!', 'ok!', 'ok!', 'no!'], dtype='<U3')

In [27]:
import pandas as pd

In [28]:
ser = pd.Series([2, 4, 4, 6, 7, 8])

In [29]:
ser.idxmax()

5

In [30]:
ser.idxmin()

0

In [31]:
ser.isin([6, 7])

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [32]:
ser.isin([6, 7]).sum()

2

In [33]:
df = pd.DataFrame({"aa": [1, 2, 3],
                   "bb": [2, 3, 4]})
df

aa  bb
0   1   2
1   2   3
2   3   4

In [34]:
df["aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [35]:
df["aa"][0]

1

In [36]:
df.iloc[1, 1]   # 정수 기반 인덱싱

3